"""empty message

Revision ID: 398c43fca077
Revises: 
Create Date: 2020-06-02 15:13:52.927979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '398c43fca077'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('cuisine', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('total_fat', sa.Integer(), nullable=False),
    sa.Column('cholesterol', sa.Integer(), nullable=False),
    sa.Column('sodium', sa.Integer(), nullable=False),
    sa.Column('total_carbs', sa.Integer(), nullable=False),
    sa.Column('protein', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('restaurants')
    # ### end Alembic commands ###
